# Find more information on toml format here:  https://github.com/toml-lang/toml

# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader = "javafml"
#This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
loaderVersion = "[36,)"
license = "GPL-3.0"
issueTrackerURL="https://github.com/LucunJi/uusi-aurinko/issues"
# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]]
modId = "uusi-aurinko"
# The version number of the mod - there's a few well known ${} variables useable here or just hardcode it
# ${file.jarVersion} will substitute the value of the Implementation-Version as read from the mod's JAR file metadata
# see the associated build.gradle script for how to populate this completely automatically during a build
version = "${file.jarVersion}"
displayName = "Uusi Aurinko"
# A URL to query for updates for this mod. See the JSON update specification <here>
#updateJSONURL="http://myurl.me/" #optional
# A URL for the "homepage" for this mod, displayed in the mod UI
#displayURL="http://example.com/" #optional
# A file name (in the root of the mod JAR) containing a logo for display
logoFile="uusi-aurinko.png" #optional

credits="Thanks for the developers of the awesome game Noita"
authors = "LucunJi, Xe_Kr, Neubulaeko"
description = '''
Something from Noita game. Give your game a glorious ending.
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.uusi-aurinko]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
# An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
ordering = "NONE"
# Side this dependency is applied on - BOTH, CLIENT or SERVER
side = "BOTH"

[[dependencies.uusi-aurinko]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,1.17)"
ordering = "NONE"
side = "BOTH"
